### ISSUE TITLE
Keycloak example uses old versions

### ISSUE THREAD

**Issue by xgp** [elestio-examples/terraform-elestio-keycloak-cluster#1]
The `jboss/keycloak` docker images are the old images that use the Wildfly server. These images are all deprecated and have security issues. The current repo is on quay here https://quay.io/repository/keycloak/keycloak and the documentation is here:

- https://www.keycloak.org/getting-started/getting-started-docker
- https://www.keycloak.org/server/all-config (Note that all of the environment variables have changed names since the switch from Wildfly to Quarkus)

**Comment by xgp** [comment]
Also, I notice that you use `JDBC_PING`. There is a long discussion and solution about how to use it with the new Quarkus version here https://keycloak.discourse.group/t/use-of-jdbc-ping-with-keycloak-17-quarkus-distro/13571

**Comment by adamkrim** [comment]
Thank you @xgp for your feedback. I'll try a configuration with the new docker image and open a pull request if it works!

**Comment by adamkrim** [comment]
In this PR #3 I use the new image
