### ISSUE TITLE
Example suggests clustering, but Infinispan ports are not open/secure

### ISSUE THREAD

**Issue by xgp** [elestio-examples/terraform-elestio-keycloak-cluster#2]
The documentation of the example appears to suggest that it supports clustering of Keycloak nodes, but other than the `JDBC_PING` setup and JGroups port (7600) being open, I don't see any actual Infinispan ports open (7800, 57800). Furthermore, if you are doing Infinispan clustering over the open internet, you would need to secure the traffic with certs, as Infinispan's protocol sends data in the clear.

I see two options:
1. open the required ports to the internet and set up certs so Infinispan can use encryption.
2. use Nebula to communicate between instances, which handles encryption for you. I did a test a long time ago with the new/Quarkus Keycloak version, `JDBC_PING` for JGroups discovery, and Nebula for Infinispan communication over port 7800 here https://github.com/xgp/elestio-keycloak

**Comment by adamkrim** [comment]
In this PR #3, I updated the docker-compose. I've checked and the nodes are well-linked.
Can you review the PR and tell me if it suits you?
